import { ScholarshipProgram } from './types';

export const scholarshipPrograms: ScholarshipProgram[] = [
    // European Scholarships
    {
        id: 'erasmus-mundus-ml',
        programName: 'Master in Machine Learning',
        universityName: 'KU Leuven, Aalto University, Universitat Politècnica de Catalunya',
        country: 'Belgium, Finland, Spain',
        city: 'Multiple Cities',
        region: 'Europe',
        academicLevel: ['Master'],
        fieldsOfStudy: ['Computer Science', 'Artificial Intelligence', 'Data Science', 'Machine Learning'],
        duration: '2 years',
        languageOfInstruction: 'English',
        scholarshipName: 'Erasmus Mundus Joint Master Scholarship',
        scholarshipType: 'Full',
        fundingOrganization: 'European Commission',
        coverage: {
            tuition: true,
            tuitionAmount: 9000,
            livingStipend: true,
            stipendAmount: 1400,
            housing: false,
            travel: true,
            travelAmount: 3000,
            healthInsurance: true,
            estimatedTotalValue: 49000,
            currency: 'EUR'
        },
        requirements: {
            minimumGPA: 3.0,
            requiredDegree: ['Bachelor in Computer Science', 'Bachelor in Mathematics', 'Bachelor in Engineering'],
            languageRequirements: [{ language: 'English', test: 'IELTS', minimumScore: '6.5' }],
            otherRequirements: ['Motivation letter', 'Two recommendation letters', 'CV']
        },
        applicationDeadline: 'January 15, 2026',
        programStartDate: 'September 2026',
        programUrl: 'https://www.mlfpm.eu/',
        scholarshipUrl: 'https://erasmus-plus.ec.europa.eu/opportunities/opportunities-for-individuals/students/erasmus-mundus-joint-masters',
        description: 'A prestigious two-year joint master program in Machine Learning offered by three top European universities.',
        benefits: ['Full tuition waiver', 'Monthly living allowance of €1,400', 'Travel and installation costs', 'Health insurance'],
        competitiveness: 'Very High'
    },
    {
        id: 'daad-development',
        programName: 'Development-Related Postgraduate Courses',
        universityName: 'Various German Universities',
        country: 'Germany',
        city: 'Multiple Cities',
        region: 'Europe',
        academicLevel: ['Master', 'PhD'],
        fieldsOfStudy: ['Development Studies', 'Economics', 'Engineering', 'Public Policy', 'Environmental Science'],
        duration: '1-2 years',
        languageOfInstruction: 'English',
        scholarshipName: 'DAAD Development-Related Postgraduate Courses',
        scholarshipType: 'Full',
        fundingOrganization: 'German Academic Exchange Service (DAAD)',
        coverage: {
            tuition: true,
            tuitionAmount: 0,
            livingStipend: true,
            stipendAmount: 934,
            housing: false,
            travel: true,
            travelAmount: 1500,
            healthInsurance: true,
            estimatedTotalValue: 30000,
            currency: 'EUR'
        },
        requirements: {
            minimumGPA: 2.75,
            requiredDegree: ['Bachelor degree with at least 4 years'],
            workExperience: 2,
            languageRequirements: [{ language: 'English', test: 'IELTS', minimumScore: '6.0' }],
            nationality: ['Developing countries'],
            otherRequirements: ['Work experience in development field', 'Employer recommendation']
        },
        applicationDeadline: 'October 15, 2025',
        programStartDate: 'October 2026',
        programUrl: 'https://www.daad.de/en/study-and-research-in-germany/',
        scholarshipUrl: 'https://www.daad.de/en/study-research-teach-abroad/scholarships/',
        description: 'DAAD scholarships for future leaders from developing countries to pursue postgraduate studies in Germany.',
        benefits: ['Monthly scholarship of €934', 'Travel allowance', 'Health insurance', 'Study and research allowance'],
        competitiveness: 'High'
    },
    {
        id: 'chevening-uk',
        programName: 'Chevening Scholarship',
        universityName: 'Any UK University',
        country: 'United Kingdom',
        city: 'Various',
        region: 'Europe',
        academicLevel: ['Master'],
        fieldsOfStudy: ['All Fields'],
        duration: '1 year',
        languageOfInstruction: 'English',
        scholarshipName: 'Chevening Scholarship',
        scholarshipType: 'Full',
        fundingOrganization: 'UK Foreign, Commonwealth and Development Office',
        coverage: {
            tuition: true,
            tuitionAmount: 18000,
            livingStipend: true,
            stipendAmount: 1500,
            housing: false,
            travel: true,
            travelAmount: 1800,
            healthInsurance: true,
            estimatedTotalValue: 40000,
            currency: 'GBP'
        },
        requirements: {
            requiredDegree: ['Bachelor degree'],
            workExperience: 2,
            languageRequirements: [{ language: 'English', test: 'IELTS', minimumScore: '6.5' }],
            nationality: ['Chevening-eligible countries'],
            otherRequirements: ['Leadership potential', 'Clear career plan', 'Return to home country commitment']
        },
        applicationDeadline: 'November 7, 2025',
        programStartDate: 'September 2026',
        programUrl: 'https://www.chevening.org/',
        scholarshipUrl: 'https://www.chevening.org/scholarships/',
        description: 'UK government\'s global scholarship programme for future leaders to study in the United Kingdom.',
        benefits: ['Full tuition fees', 'Monthly living allowance', 'Return flights', 'Additional grants for thesis and networking'],
        competitiveness: 'Very High'
    },
    {
        id: 'gates-cambridge',
        programName: 'Gates Cambridge Scholarship',
        universityName: 'University of Cambridge',
        country: 'United Kingdom',
        city: 'Cambridge',
        region: 'Europe',
        academicLevel: ['Master', 'PhD'],
        fieldsOfStudy: ['All Fields'],
        duration: '1-4 years',
        languageOfInstruction: 'English',
        scholarshipName: 'Gates Cambridge Scholarship',
        scholarshipType: 'Full',
        fundingOrganization: 'Bill and Melinda Gates Foundation',
        coverage: {
            tuition: true,
            tuitionAmount: 45000,
            livingStipend: true,
            stipendAmount: 1800,
            housing: false,
            travel: true,
            travelAmount: 2000,
            healthInsurance: true,
            estimatedTotalValue: 80000,
            currency: 'GBP'
        },
        requirements: {
            minimumGPA: 3.7,
            requiredDegree: ['Outstanding undergraduate degree'],
            languageRequirements: [{ language: 'English', test: 'IELTS', minimumScore: '7.5' }],
            nationality: ['Non-UK citizens'],
            otherRequirements: ['Outstanding academic record', 'Leadership potential', 'Commitment to improving lives of others']
        },
        applicationDeadline: 'December 3, 2025',
        programStartDate: 'October 2026',
        programUrl: 'https://www.cam.ac.uk/',
        scholarshipUrl: 'https://www.gatescambridge.org/',
        description: 'One of the most prestigious international scholarships, supporting outstanding students from around the world.',
        benefits: ['Full tuition fees', 'Maintenance allowance', 'Travel costs', 'Family allowance if applicable', 'Academic development funding'],
        competitiveness: 'Very High'
    },
    {
        id: 'eth-excellence',
        programName: 'ETH Excellence Scholarship',
        universityName: 'ETH Zurich',
        country: 'Switzerland',
        city: 'Zurich',
        region: 'Europe',
        academicLevel: ['Master'],
        fieldsOfStudy: ['Engineering', 'Computer Science', 'Natural Sciences', 'Mathematics'],
        duration: '2 years',
        languageOfInstruction: 'English',
        scholarshipName: 'ETH Excellence Master Scholarship (ESOP)',
        scholarshipType: 'Full',
        fundingOrganization: 'ETH Zurich Foundation',
        coverage: {
            tuition: true,
            tuitionAmount: 1460,
            livingStipend: true,
            stipendAmount: 1850,
            housing: false,
            travel: false,
            healthInsurance: false,
            estimatedTotalValue: 50000,
            currency: 'CHF'
        },
        requirements: {
            minimumGPA: 3.8,
            requiredDegree: ['Top 5% of Bachelor class'],
            languageRequirements: [{ language: 'English', test: 'TOEFL', minimumScore: '100' }],
            otherRequirements: ['Outstanding academic achievement', 'Research experience preferred']
        },
        applicationDeadline: 'December 15, 2025',
        programStartDate: 'September 2026',
        programUrl: 'https://ethz.ch/en/studies/master.html',
        scholarshipUrl: 'https://ethz.ch/students/en/studies/financial/scholarships/excellencescholarship.html',
        description: 'ETH Zurich\'s most prestigious scholarship for outstanding master students in science and engineering.',
        benefits: ['Full tuition waiver', 'Living stipend CHF 1,850/month', 'Research opportunities'],
        competitiveness: 'Very High'
    },
    // North American Scholarships
    {
        id: 'fulbright-usa',
        programName: 'Fulbright Foreign Student Program',
        universityName: 'Any US University',
        country: 'United States',
        city: 'Various',
        region: 'North America',
        academicLevel: ['Master', 'PhD'],
        fieldsOfStudy: ['All Fields'],
        duration: '1-2 years',
        languageOfInstruction: 'English',
        scholarshipName: 'Fulbright Foreign Student Program',
        scholarshipType: 'Full',
        fundingOrganization: 'U.S. Department of State',
        coverage: {
            tuition: true,
            tuitionAmount: 50000,
            livingStipend: true,
            stipendAmount: 2000,
            housing: false,
            travel: true,
            travelAmount: 2500,
            healthInsurance: true,
            estimatedTotalValue: 90000,
            currency: 'USD'
        },
        requirements: {
            minimumGPA: 3.0,
            requiredDegree: ['Bachelor degree'],
            languageRequirements: [{ language: 'English', test: 'TOEFL', minimumScore: '90' }],
            nationality: ['Fulbright-eligible countries'],
            otherRequirements: ['Strong academic record', 'Leadership qualities', 'Community engagement']
        },
        applicationDeadline: 'February 1, 2026',
        programStartDate: 'August 2026',
        programUrl: 'https://foreign.fulbrightonline.org/',
        scholarshipUrl: 'https://foreign.fulbrightonline.org/about/foreign-student-program',
        description: 'The flagship international educational exchange program sponsored by the U.S. government.',
        benefits: ['Full tuition and fees', 'Monthly living stipend', 'Round-trip airfare', 'Health insurance', 'Cultural enrichment activities'],
        competitiveness: 'Very High'
    },
    {
        id: 'stanford-knight-hennessy',
        programName: 'Knight-Hennessy Scholars',
        universityName: 'Stanford University',
        country: 'United States',
        city: 'Stanford, California',
        region: 'North America',
        academicLevel: ['Master', 'PhD'],
        fieldsOfStudy: ['All Fields'],
        duration: '2-4 years',
        languageOfInstruction: 'English',
        scholarshipName: 'Knight-Hennessy Scholarship',
        scholarshipType: 'Full',
        fundingOrganization: 'Knight-Hennessy Scholars Program',
        coverage: {
            tuition: true,
            tuitionAmount: 60000,
            livingStipend: true,
            stipendAmount: 2500,
            housing: false,
            travel: true,
            travelAmount: 3000,
            healthInsurance: true,
            estimatedTotalValue: 150000,
            currency: 'USD'
        },
        requirements: {
            minimumGPA: 3.7,
            requiredDegree: ['Bachelor degree within last 4 years'],
            languageRequirements: [{ language: 'English', test: 'TOEFL', minimumScore: '100' }],
            otherRequirements: ['Demonstrated leadership', 'Civic commitment', 'Clear career vision']
        },
        applicationDeadline: 'October 9, 2025',
        programStartDate: 'September 2026',
        programUrl: 'https://www.stanford.edu/',
        scholarshipUrl: 'https://knight-hennessy.stanford.edu/',
        description: 'Stanford\'s flagship scholarship developing community of future global leaders.',
        benefits: ['Full tuition for graduate program', 'Living stipend', 'Travel costs', 'Leadership development programming'],
        competitiveness: 'Very High'
    },
    {
        id: 'vanier-canada',
        programName: 'Vanier Canada Graduate Scholarships',
        universityName: 'Any Canadian University',
        country: 'Canada',
        city: 'Various',
        region: 'North America',
        academicLevel: ['PhD'],
        fieldsOfStudy: ['All Fields'],
        duration: '3 years',
        languageOfInstruction: 'English',
        scholarshipName: 'Vanier Canada Graduate Scholarship',
        scholarshipType: 'Full',
        fundingOrganization: 'Government of Canada',
        coverage: {
            tuition: true,
            tuitionAmount: 20000,
            livingStipend: true,
            stipendAmount: 4166,
            housing: false,
            travel: false,
            healthInsurance: false,
            estimatedTotalValue: 150000,
            currency: 'CAD'
        },
        requirements: {
            minimumGPA: 3.5,
            requiredDegree: ['Master degree or equivalent'],
            languageRequirements: [{ language: 'English', test: 'IELTS', minimumScore: '7.0' }],
            otherRequirements: ['Exceptional research potential', 'Leadership skills', 'Admitted to PhD program']
        },
        applicationDeadline: 'November 1, 2025',
        programStartDate: 'September 2026',
        programUrl: 'https://vanier.gc.ca/',
        scholarshipUrl: 'https://vanier.gc.ca/en/home-accueil.html',
        description: 'Canada\'s most prestigious doctoral scholarship attracting world-class researchers.',
        benefits: ['$50,000 CAD per year for 3 years', 'Research support', 'Prestigious network'],
        competitiveness: 'Very High'
    },
    // Asian Scholarships
    {
        id: 'mext-japan',
        programName: 'MEXT Research Student Scholarship',
        universityName: 'Various Japanese Universities',
        country: 'Japan',
        city: 'Various',
        region: 'Asia',
        academicLevel: ['Master', 'PhD'],
        fieldsOfStudy: ['All Fields'],
        duration: '2-5 years',
        languageOfInstruction: 'Japanese/English',
        scholarshipName: 'MEXT (Monbukagakusho) Scholarship',
        scholarshipType: 'Full',
        fundingOrganization: 'Japanese Ministry of Education',
        coverage: {
            tuition: true,
            tuitionAmount: 0,
            livingStipend: true,
            stipendAmount: 145000,
            housing: false,
            travel: true,
            travelAmount: 200000,
            healthInsurance: false,
            estimatedTotalValue: 5000000,
            currency: 'JPY'
        },
        requirements: {
            requiredDegree: ['Bachelor or Master degree'],
            ageLimit: 35,
            languageRequirements: [],
            otherRequirements: ['Interest in Japan', 'Clear research plan', 'Willing to learn Japanese']
        },
        applicationDeadline: 'April 15, 2026',
        programStartDate: 'October 2026',
        programUrl: 'https://www.mext.go.jp/',
        scholarshipUrl: 'https://www.studyinjapan.go.jp/en/smap-stopj-applications-research.html',
        description: 'Japanese government scholarship for international students pursuing research in Japan.',
        benefits: ['Full tuition exemption', 'Monthly allowance ¥145,000', 'Round-trip airfare', 'Japanese language training'],
        competitiveness: 'High'
    },
    {
        id: 'kgsp-korea',
        programName: 'Korean Government Scholarship Program',
        universityName: 'Various Korean Universities',
        country: 'South Korea',
        city: 'Various',
        region: 'Asia',
        academicLevel: ['Bachelor', 'Master', 'PhD'],
        fieldsOfStudy: ['All Fields'],
        duration: '2-5 years',
        languageOfInstruction: 'Korean/English',
        scholarshipName: 'Global Korea Scholarship (GKS)',
        scholarshipType: 'Full',
        fundingOrganization: 'National Institute for International Education',
        coverage: {
            tuition: true,
            tuitionAmount: 0,
            livingStipend: true,
            stipendAmount: 1000000,
            housing: false,
            travel: true,
            travelAmount: 1500000,
            healthInsurance: true,
            estimatedTotalValue: 40000000,
            currency: 'KRW'
        },
        requirements: {
            minimumGPA: 2.64,
            requiredDegree: ['Previous degree completed'],
            ageLimit: 40,
            languageRequirements: [],
            otherRequirements: ['Good health', 'No previous GKS award', 'Korean language training included']
        },
        applicationDeadline: 'March 31, 2026',
        programStartDate: 'September 2026',
        programUrl: 'https://www.studyinkorea.go.kr/',
        scholarshipUrl: 'https://www.studyinkorea.go.kr/en/sub/gks/allnew_invite.do',
        description: 'South Korean government scholarship promoting international exchange and mutual friendship.',
        benefits: ['Full tuition', 'Monthly allowance', 'Settlement allowance', 'Korean language training', 'Round-trip airfare', 'Medical insurance'],
        competitiveness: 'High'
    },
    {
        id: 'csc-china',
        programName: 'Chinese Government Scholarship',
        universityName: 'Various Chinese Universities',
        country: 'China',
        city: 'Various',
        region: 'Asia',
        academicLevel: ['Bachelor', 'Master', 'PhD'],
        fieldsOfStudy: ['All Fields'],
        duration: '1-6 years',
        languageOfInstruction: 'Chinese/English',
        scholarshipName: 'Chinese Government Scholarship (CSC)',
        scholarshipType: 'Full',
        fundingOrganization: 'China Scholarship Council',
        coverage: {
            tuition: true,
            tuitionAmount: 0,
            livingStipend: true,
            stipendAmount: 3500,
            housing: true,
            travel: false,
            healthInsurance: true,
            estimatedTotalValue: 60000,
            currency: 'CNY'
        },
        requirements: {
            requiredDegree: ['Appropriate previous degree'],
            ageLimit: 35,
            languageRequirements: [{ language: 'Chinese/English', test: 'HSK/IELTS', minimumScore: 'HSK4 or IELTS 6.0' }],
            otherRequirements: ['Good health', 'Research proposal for graduate studies']
        },
        applicationDeadline: 'January 31, 2026',
        programStartDate: 'September 2026',
        programUrl: 'https://www.csc.edu.cn/',
        scholarshipUrl: 'https://www.campuschina.org/',
        description: 'Full scholarship from the Chinese government for international students at top Chinese universities.',
        benefits: ['Full tuition waiver', 'Living allowance', 'Free accommodation', 'Comprehensive medical insurance'],
        competitiveness: 'Medium'
    },
    {
        id: 'nus-research',
        programName: 'NUS Research Scholarship',
        universityName: 'National University of Singapore',
        country: 'Singapore',
        city: 'Singapore',
        region: 'Asia',
        academicLevel: ['PhD'],
        fieldsOfStudy: ['Engineering', 'Computer Science', 'Business', 'Sciences', 'Social Sciences'],
        duration: '4 years',
        languageOfInstruction: 'English',
        scholarshipName: 'NUS Research Scholarship',
        scholarshipType: 'Full',
        fundingOrganization: 'National University of Singapore',
        coverage: {
            tuition: true,
            tuitionAmount: 42000,
            livingStipend: true,
            stipendAmount: 2700,
            housing: false,
            travel: false,
            healthInsurance: false,
            estimatedTotalValue: 180000,
            currency: 'SGD'
        },
        requirements: {
            minimumGPA: 3.5,
            requiredDegree: ['Bachelor or Master degree with honors'],
            languageRequirements: [{ language: 'English', test: 'TOEFL', minimumScore: '85' }],
            otherRequirements: ['Strong research potential', 'Research proposal', 'Faculty endorsement']
        },
        applicationDeadline: 'November 15, 2025',
        programStartDate: 'August 2026',
        programUrl: 'https://www.nus.edu.sg/',
        scholarshipUrl: 'https://nusgs.nus.edu.sg/scholarships/',
        description: 'Full PhD scholarship at Asia\'s top-ranked university with world-class research facilities.',
        benefits: ['Full tuition subsidy', 'Monthly stipend S$2,700-3,200', 'Research support'],
        competitiveness: 'High'
    },
    // Oceania
    {
        id: 'australia-awards',
        programName: 'Australia Awards Scholarships',
        universityName: 'Various Australian Universities',
        country: 'Australia',
        city: 'Various',
        region: 'Oceania',
        academicLevel: ['Master', 'PhD'],
        fieldsOfStudy: ['All Fields aligned with development'],
        duration: '1-4 years',
        languageOfInstruction: 'English',
        scholarshipName: 'Australia Awards Scholarship',
        scholarshipType: 'Full',
        fundingOrganization: 'Australian Government',
        coverage: {
            tuition: true,
            tuitionAmount: 45000,
            livingStipend: true,
            stipendAmount: 3400,
            housing: false,
            travel: true,
            travelAmount: 5000,
            healthInsurance: true,
            estimatedTotalValue: 200000,
            currency: 'AUD'
        },
        requirements: {
            requiredDegree: ['Bachelor degree'],
            workExperience: 2,
            languageRequirements: [{ language: 'English', test: 'IELTS', minimumScore: '6.5' }],
            nationality: ['Partner countries in Indo-Pacific'],
            otherRequirements: ['Return to home country for 2 years', 'Leadership potential']
        },
        applicationDeadline: 'April 30, 2026',
        programStartDate: 'February 2027',
        programUrl: 'https://www.australiaawards.gov.au/',
        scholarshipUrl: 'https://www.dfat.gov.au/people-to-people/australia-awards',
        description: 'Australian government scholarships for emerging leaders from developing countries.',
        benefits: ['Full tuition fees', 'Living allowance', 'Return air travel', 'Establishment allowance', 'Health insurance', 'Pre-departure training'],
        competitiveness: 'High'
    },
    {
        id: 'nz-postgrad',
        programName: 'New Zealand Scholarships',
        universityName: 'Various New Zealand Universities',
        country: 'New Zealand',
        city: 'Various',
        region: 'Oceania',
        academicLevel: ['Master', 'PhD'],
        fieldsOfStudy: ['All Fields'],
        duration: '1-3 years',
        languageOfInstruction: 'English',
        scholarshipName: 'New Zealand Scholarships',
        scholarshipType: 'Full',
        fundingOrganization: 'New Zealand Ministry of Foreign Affairs',
        coverage: {
            tuition: true,
            tuitionAmount: 35000,
            livingStipend: true,
            stipendAmount: 2000,
            housing: false,
            travel: true,
            travelAmount: 3000,
            healthInsurance: true,
            estimatedTotalValue: 100000,
            currency: 'NZD'
        },
        requirements: {
            requiredDegree: ['Bachelor degree'],
            languageRequirements: [{ language: 'English', test: 'IELTS', minimumScore: '6.5' }],
            nationality: ['Pacific and developing countries'],
            otherRequirements: ['Work experience preferred', 'Leadership qualities']
        },
        applicationDeadline: 'March 28, 2026',
        programStartDate: 'February 2027',
        programUrl: 'https://www.studywithnewzealand.govt.nz/',
        scholarshipUrl: 'https://www.mfat.govt.nz/en/aid-and-development/new-zealand-government-scholarships/',
        description: 'New Zealand government scholarships supporting the development of partner countries.',
        benefits: ['Full tuition', 'Living allowance', 'Travel costs', 'Research support', 'Health insurance'],
        competitiveness: 'Medium'
    },
    // Additional Programs
    {
        id: 'swiss-excellence',
        programName: 'Swiss Government Excellence Scholarships',
        universityName: 'Various Swiss Universities',
        country: 'Switzerland',
        city: 'Various',
        region: 'Europe',
        academicLevel: ['PhD', 'Postgraduate'],
        fieldsOfStudy: ['All Fields', 'Arts'],
        duration: '1-3 years',
        languageOfInstruction: 'German/French/Italian/English',
        scholarshipName: 'Swiss Government Excellence Scholarship',
        scholarshipType: 'Full',
        fundingOrganization: 'Swiss Government',
        coverage: {
            tuition: true,
            tuitionAmount: 0,
            livingStipend: true,
            stipendAmount: 1920,
            housing: false,
            travel: true,
            travelAmount: 2500,
            healthInsurance: true,
            estimatedTotalValue: 70000,
            currency: 'CHF'
        },
        requirements: {
            requiredDegree: ['Master degree'],
            ageLimit: 35,
            languageRequirements: [],
            otherRequirements: ['Research proposal accepted by Swiss university', 'Host professor confirmation']
        },
        applicationDeadline: 'November 15, 2025',
        programStartDate: 'September 2026',
        programUrl: 'https://www.sbfi.admin.ch/',
        scholarshipUrl: 'https://www.sbfi.admin.ch/sbfi/en/home/education/scholarships-and-grants/swiss-government-excellence-scholarships.html',
        description: 'Swiss government scholarships for researchers and artists from around the world.',
        benefits: ['Monthly allowance CHF 1,920', 'Tuition waiver', 'Health insurance', 'Airfare', 'Housing allowance'],
        competitiveness: 'High'
    },
    {
        id: 'denmarks-scholarship',
        programName: 'Danish Government Scholarship',
        universityName: 'Various Danish Universities',
        country: 'Denmark',
        city: 'Various',
        region: 'Europe',
        academicLevel: ['Master'],
        fieldsOfStudy: ['All Fields'],
        duration: '2 years',
        languageOfInstruction: 'English',
        scholarshipName: 'Danish Government Scholarship',
        scholarshipType: 'Partial',
        fundingOrganization: 'Danish Ministry of Higher Education',
        coverage: {
            tuition: true,
            tuitionAmount: 15000,
            livingStipend: true,
            stipendAmount: 6000,
            housing: false,
            travel: false,
            healthInsurance: false,
            estimatedTotalValue: 50000,
            currency: 'DKK'
        },
        requirements: {
            minimumGPA: 3.0,
            requiredDegree: ['Bachelor degree'],
            languageRequirements: [{ language: 'English', test: 'IELTS', minimumScore: '6.5' }],
            nationality: ['Non-EU/EEA countries'],
            otherRequirements: ['Relevant academic background']
        },
        applicationDeadline: 'March 1, 2026',
        programStartDate: 'September 2026',
        programUrl: 'https://studyindenmark.dk/',
        scholarshipUrl: 'https://studyindenmark.dk/study-options/danish-government-scholarships',
        description: 'Scholarships for highly qualified international students from non-EU countries.',
        benefits: ['Full or partial tuition waiver', 'Monthly grant DKK 6,000'],
        competitiveness: 'Medium'
    },
    {
        id: 'netherlands-fellowship',
        programName: 'Netherlands Fellowship Programmes',
        universityName: 'Various Dutch Universities',
        country: 'Netherlands',
        city: 'Various',
        region: 'Europe',
        academicLevel: ['Master', 'Certificate'],
        fieldsOfStudy: ['Development Studies', 'Public Health', 'Agriculture', 'Environment'],
        duration: '1-2 years',
        languageOfInstruction: 'English',
        scholarshipName: 'NFP - Netherlands Fellowship Programme',
        scholarshipType: 'Full',
        fundingOrganization: 'Dutch Ministry of Foreign Affairs',
        coverage: {
            tuition: true,
            tuitionAmount: 20000,
            livingStipend: true,
            stipendAmount: 1050,
            housing: false,
            travel: true,
            travelAmount: 2000,
            healthInsurance: true,
            estimatedTotalValue: 45000,
            currency: 'EUR'
        },
        requirements: {
            requiredDegree: ['Bachelor degree'],
            workExperience: 3,
            languageRequirements: [{ language: 'English', test: 'IELTS', minimumScore: '6.0' }],
            nationality: ['NFP-eligible countries'],
            ageLimit: 45,
            otherRequirements: ['Employer endorsement', 'Return to home country commitment']
        },
        applicationDeadline: 'October 1, 2025',
        programStartDate: 'September 2026',
        programUrl: 'https://www.nuffic.nl/',
        scholarshipUrl: 'https://www.nuffic.nl/en/subjects/nfp/',
        description: 'Dutch fellowships for mid-career professionals from developing countries.',
        benefits: ['Full tuition waiver', 'Monthly living allowance', 'Travel costs', 'Visa costs', 'Insurance'],
        competitiveness: 'Medium'
    },
    {
        id: 'aga-khan-foundation',
        programName: 'Aga Khan Foundation International Scholarship',
        universityName: 'Various Top Universities Worldwide',
        country: 'Global',
        city: 'Various',
        region: 'Global',
        academicLevel: ['Master', 'PhD'],
        fieldsOfStudy: ['All Fields'],
        duration: '1-4 years',
        languageOfInstruction: 'English',
        scholarshipName: 'AKF International Scholarship Programme',
        scholarshipType: 'Partial',
        fundingOrganization: 'Aga Khan Foundation',
        coverage: {
            tuition: true,
            tuitionAmount: 30000,
            livingStipend: true,
            stipendAmount: 1500,
            housing: false,
            travel: true,
            travelAmount: 1500,
            healthInsurance: false,
            estimatedTotalValue: 60000,
            currency: 'USD'
        },
        requirements: {
            requiredDegree: ['Bachelor degree with excellent grades'],
            workExperience: 2,
            languageRequirements: [{ language: 'English', test: 'IELTS', minimumScore: '6.5' }],
            nationality: ['AKF-eligible countries'],
            otherRequirements: ['Financial need', 'Admission to reputable university', 'Commitment to development']
        },
        applicationDeadline: 'March 31, 2026',
        programStartDate: 'September 2026',
        programUrl: 'https://www.akdn.org/',
        scholarshipUrl: 'https://www.akdn.org/our-agencies/aga-khan-foundation/international-scholarship-programme',
        description: 'Need-based scholarships for students from developing countries with no access to other funding.',
        benefits: ['50% scholarship (grant)', '50% loan (interest-free)', 'Travel support', 'Living expenses'],
        competitiveness: 'Medium'
    },
    {
        id: 'oxford-clarendon',
        programName: 'Clarendon Scholarships',
        universityName: 'University of Oxford',
        country: 'United Kingdom',
        city: 'Oxford',
        region: 'Europe',
        academicLevel: ['Master', 'PhD'],
        fieldsOfStudy: ['All Fields'],
        duration: '1-4 years',
        languageOfInstruction: 'English',
        scholarshipName: 'Clarendon Scholarship',
        scholarshipType: 'Full',
        fundingOrganization: 'Oxford University Press',
        coverage: {
            tuition: true,
            tuitionAmount: 30000,
            livingStipend: true,
            stipendAmount: 1500,
            housing: false,
            travel: false,
            healthInsurance: false,
            estimatedTotalValue: 50000,
            currency: 'GBP'
        },
        requirements: {
            minimumGPA: 3.7,
            requiredDegree: ['Outstanding undergraduate or Master degree'],
            languageRequirements: [{ language: 'English', test: 'IELTS', minimumScore: '7.5' }],
            otherRequirements: ['Academic excellence', 'Research potential', 'Automatically considered upon application']
        },
        applicationDeadline: 'January 6, 2026',
        programStartDate: 'October 2026',
        programUrl: 'https://www.ox.ac.uk/',
        scholarshipUrl: 'https://www.ox.ac.uk/clarendon/',
        description: 'Oxford\'s largest scholarship fund, awarded based purely on academic merit.',
        benefits: ['Full tuition fees', 'Living expenses grant', 'Academic networking'],
        competitiveness: 'Very High'
    }
];

// Helper function to get programs by field of study
export function getProgramsByField(field: string): ScholarshipProgram[] {
    return scholarshipPrograms.filter(program =>
        program.fieldsOfStudy.some(f =>
            f.toLowerCase().includes(field.toLowerCase()) ||
            f === 'All Fields'
        )
    );
}

// Helper function to get programs by region
export function getProgramsByRegion(region: string): ScholarshipProgram[] {
    return scholarshipPrograms.filter(program =>
        program.region.toLowerCase() === region.toLowerCase()
    );
}

// Helper function to get programs by level
export function getProgramsByLevel(level: string): ScholarshipProgram[] {
    return scholarshipPrograms.filter(program =>
        program.academicLevel.some(l => l.toLowerCase() === level.toLowerCase())
    );
}

// Helper function to get fully funded programs
export function getFullyFundedPrograms(): ScholarshipProgram[] {
    return scholarshipPrograms.filter(program =>
        program.scholarshipType === 'Full' || program.scholarshipType === 'Fellowship'
    );
}
